force-app/main/default/objects/Charge_Type__c/Charge_Type__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the charge type we apply to our clients</description>
    <label>Charge Type</label>
    <nameField>
        <label>Charge Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Type__c/recordTypes/Cost.recordType-meta.xml
<RecordType>
    <fullName>Cost</fullName>
    <active>true</active>
    <label>Cost</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to specify the legal country of the contact</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the current products held in N26 related to the contact</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object used to hold the country information and its coin</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Field used to indicate the currency of a country</description>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the current products information for contacts, based on the plan type and their specific home country</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>This field is generated automatically based on the Home Country currency field</description>
    <formula>TEXT(Home_Country__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is generated automatically based on the Home Country currency field</inlineHelpText>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Home Country record</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related charge type</description>
    <label>Type</label>
    <referenceTo>Charge_Type__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Value_Number__c</fullName>
    <description>Field used to display the numeric value of the record</description>
    <label>Value Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/recordTypes/Cost.recordType-meta.xml
<RecordType>
    <fullName>Cost</fullName>
    <active>true</active>
    <description>Recordtype to specify when a product info is a cost</description>
    <label>Cost</label>
</RecordType>

force-app/main/default/classes/ProductInformationTriggerHandlerTest.cls
@IsTest
private class ProductInformationTriggerHandlerTest {

    @TestSetup
    static void setupData() {
        //we create the product
        Product2 p = new Product2(
            Name = 'Standard',
            ProductCode = 'Standard'
        );
        insert p;

        // Create Home Country
        Country__c hc = new Country__c(
            Name = 'ES',
            Currency__c='EUR'
        );
        insert hc;

        //Create charge type
        Charge_Type__c ct = new Charge_Type__c(
            Name = 'Cost per Calendar Month',
            RecordTypeId= Schema.SObjectType.Charge_Type__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert ct;

        // Create Product Information linked to Contact
        Product_Information__c pi = new Product_Information__c(
            Product__c = p.Id,
            Home_Country__c = hc.Id,
            Type__c=ct.Id,
            Value_Number__c = 0,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi;
    }

    @IsTest
    static void test_DuplicateInPI() {
        //test for duplicates in DB

        Product2 p = [SELECT Id FROM Product2 WHERE Name = 'Standard' LIMIT 1];
        Country__c hc = [SELECT Id FROM Country__c WHERE Name = 'ES' LIMIT 1];
        Charge_Type__c ct = [SELECT Id FROM Charge_Type__c WHERE Name = 'Cost per Calendar Month' LIMIT 1];

        Product_Information__c pi = new Product_Information__c(
            Product__c = p.Id,
            Home_Country__c = hc.Id,
            Type__c=ct.Id,
            Value_Number__c = 6,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi;

        Test.startTest();
            Database.SaveResult sr = Database.insert(pi, false);
        Test.stopTest();

        System.assert(!sr.isSuccess(), 'Fail due to duplicate');
    }

    @IsTest
    static void test_DuplicateInSameTransaction() {
        //test for duplicates in the same insertion

        Product2 p = new Product2(
            Name = 'Metal',
            ProductCode = 'Metal'
        );
        insert p;

        Country__c hc = [SELECT Id FROM Country__c WHERE Name = 'ES' LIMIT 1];
        Charge_Type__c ct = [SELECT Id FROM Charge_Type__c WHERE Name = 'Cost per Calendar Month' LIMIT 1];


        // Create Product Information linked to Contact
        Product_Information__c pi1 = new Product_Information__c(
            Product__c = p.Id,
            Home_Country__c = hc.Id,
            Type__c=ct.Id,
            Value_Number__c = 0,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi1;

        Product_Information__c pi2 = new Product_Information__c(
            Product__c = p.Id,
            Home_Country__c = hc.Id,
            Type__c=ct.Id,
            Value_Number__c = 0,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi2;

        Test.startTest();
            Database.SaveResult[] results = Database.insert(new List<Product_Information__c>{pi1, pi2}, false);
        Test.stopTest();

        System.assert(!results[1].isSuccess(), 'Fail due to duplicate in transaction');
    }

    @IsTest
    static void test_InsertRecord() {
        //test for addition of a new product
        
        Product2 p = new Product2(
            Name = 'Go',
            ProductCode = 'Go'
        );
        insert p;

        Country__c hc = [SELECT Id FROM Country__c WHERE Name = 'ES' LIMIT 1];
        Charge_Type__c ct = [SELECT Id FROM Charge_Type__c WHERE Name = 'Cost per Calendar Month' LIMIT 1];

        // Create Product Information linked to Contact
        Product_Information__c pi = new Product_Information__c(
            Product__c = p.Id,
            Home_Country__c = hc.Id,
            Type__c=ct.Id,
            Value_Number__c = 0,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi;

        Test.startTest();
            insert pi;
        Test.stopTest();

        System.assertNotEquals(null, pi.Id, 'Record inserted');
    }
}