force-app/main/default/objects/Charge_Type__c/Charge_Type__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the charge type we apply to our clients</description>
    <label>Charge Type</label>
    <nameField>
        <label>Charge Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Type__c/recordTypes/Cost.recordType-meta.xml
<RecordType>
    <fullName>Cost</fullName>
    <active>true</active>
    <label>Cost</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to specify the legal country of the contact</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the current products held in N26 related to the contact</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object used to hold the country information and its coin</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Field used to indicate the currency of a country</description>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the current products information for contacts, based on the plan type and their specific home country</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>This field is generated automatically based on the Home Country currency field</description>
    <formula>TEXT(Home_Country__r.Currency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is generated automatically based on the Home Country currency field</inlineHelpText>
    <label>Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Home Country record</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related charge type</description>
    <label>Type</label>
    <referenceTo>Charge_Type__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Value_Number__c.field-meta.xml
<CustomField>
    <fullName>Value_Number__c</fullName>
    <description>Field used to display the numeric value of the record</description>
    <label>Value Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/recordTypes/Cost.recordType-meta.xml
<RecordType>
    <fullName>Cost</fullName>
    <active>true</active>
    <description>Recordtype to specify when a product info is a cost</description>
    <label>Cost</label>
</RecordType>

force-app/main/default/classes/APIRestGetContactInfoTest.cls
@IsTest
private class APIRestGetContactInfoTest {

    @TestSetup
    static void setupData() {

        //create product
        Product2 pro = new Product2(
            Name = 'Standard',
            ProductCode = 'Standard'
        );
        insert pro;

        // Create Home Country
        Country__c hc = new Country__c(
            Name = 'ES',
            Currency__c='EUR'
        );
        insert hc;


        // Create Contact with UUID, Product, and Country
        Contact c = new Contact(
            LastName = 'N26 Contact',
            UUID__c = '12345',
            Product__c = pro.Id,
            Home_Country__c = hc.Id
        );
        insert c;


        //Create charge type
        Charge_Type__c ct = new Charge_Type__c(
            Name = 'Cost per Calendar Month',
            RecordTypeId= Schema.SObjectType.Charge_Type__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert ct;

        // Create Product Information linked to Contact
        Product_Information__c pi = new Product_Information__c(
            Product__c = c.Product__c,
            Home_Country__c = c.Home_Country__c,
            Type__c=ct.Id,
            Value_Number__c = 0,
            RecordTypeId= Schema.SObjectType.Product_Information__c.getRecordTypeInfosByName().get('Cost').getRecordTypeId()
        );
        insert pi;
    }

    @IsTest
    static void test_Success() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestUri = '/services/apexrest/api/n26/12345';//existing UUID to success
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;


        //we get the info of an existing contact
        Test.startTest();
            APIRestGetContactInfo.getContactInfo();
        Test.stopTest();

        System.assertEquals(200, RestContext.response.statusCode);
        System.assert(RestContext.response.responseBody.toString().contains('success'));
    }

    @IsTest
    static void test_NoContact() {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestUri = '/services/apexrest/api/n26/99999'; // non-existing UUID
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;


        //we try to get an error with a non existing UUID
        Test.startTest();
            APIRestGetContactInfo.getContactInfo();
        Test.stopTest();

        System.assertEquals(400, RestContext.response.statusCode);
        System.assert(RestContext.response.responseBody.toString().contains('error'));
    }
}