force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the current products information for contacts, based on the plan type and their specific home country</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Home Country record</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related charge type</description>
    <label>Type</label>
    <referenceTo>Charge_Type__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductInformationTriggerHandler.cls
public class ProductInformationTriggerHandler {

    public static void handleBeforeInsert(List<Product_Information__c> newProdInf) {
        //we ensure that we don't create duplicates
        Set<Id> productIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();
        Set<String> typeIds = new Set<String>();
        Map<String,String> existingPiKeysNames = new Map<String,String>();
        Set<String> uniquePiKeysNew = new Set<String>();

        for (Product_Information__c pi : newProdInf) {
            if (pi.Product__c != null) productIds.add(pi.Product__c);
            if (pi.Home_Country__c != null) countryIds.add(pi.Home_Country__c);
            if (pi.Type__c != null) typeIds.add(pi.Type__c);
        }

        // query for existing Product Information records, we add the current products and countries Ids to avoid hitting limits in the future
        List<Product_Information__c> existingProdInf = [
            SELECT Id, Type__c, Product__c, Home_Country__c, Name
            FROM Product_Information__c
            WHERE Product__c IN :productIds
            AND Home_Country__c IN :countryIds
            AND Type__c IN : typeIds
        ];

        //geenrate a key to control dupes
        for (Product_Information__c pi : existingProdInf) {
            existingPiKeysNames.put(pi.Type__c + '-' + pi.Home_Country__c + '-' + pi.Product__c,pi.Name);
        }

        //we ensure there are no duplicates in the DB or in the same transaction
        for (Product_Information__c pi : newProdInf) {
            String key = pi.Type__c + '-' + pi.Home_Country__c + '-' + pi.Product__c;

            // already exists in DB
            if (existingPiKeysNames.containsKey(key)) {
                pi.addError(
                    System.Label.ProductInformationTriggerHandler_ProdInfExistsError+existingPiKeysNames.get(key)
                );
            }

            // duplicated in the same transaction
            if (uniquePiKeysNew.contains(key)) {
                pi.addError(
                    System.Label.ProductInformationTriggerHandler_ProdInfAddedError
                );
            } else {
                uniquePiKeysNew.add(key);
            }
        }
    }
}