force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to specify the legal country of the contact</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the current products held in N26 related to the contact</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the current products information for contacts, based on the plan type and their specific home country</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Charge_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type_Name__c</fullName>
    <description>Formula field to display the related lookup object Charge Type name</description>
    <formula>Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Home Country record</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Value_Display__c.field-meta.xml
<CustomField>
    <fullName>Value_Display__c</fullName>
    <description>This field is generated automatically based on the values added</description>
    <formula>IF( 
   RecordType.Name = &quot;Fee&quot;,
   IF(
      Value_Percent__c = 0, 
      &quot;Free&quot;, 
      TEXT(Value_Percent__c*100) &amp; &quot;%&quot;),

   IF(
      Not_Applicable__c, 
      &quot;N/a&quot;,
      IF(
         Value_Number__c-FLOOR(Value_Number__c)=0,
         Currency_Symbol__c &amp; &quot; &quot; &amp; SUBSTITUTE(TEXT( ROUND(Value_Number__c, 2)),&quot;.&quot;,&quot;,&quot;),
         Currency_Symbol__c &amp; &quot; &quot; &amp; SUBSTITUTE(TEXT(FLOOR(Value_Number__c)) &amp; &quot;.&quot; &amp; LPAD(TEXT((Value_Number__c - FLOOR(Value_Number__c)) * 100), 2, &quot;0&quot;),&quot;.&quot;,&quot;,&quot;)
         )
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is generated automatically based on the values added</inlineHelpText>
    <label>Value Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APIRestGetContactInfo.cls
@RestResource(urlMapping='/api/n26/*')
global with sharing class APIRestGetContactInfo {
    //Allowed username to consume integration
    private static final API_Integration_User__mdt USER_INTEGRATION = [SELECT Id, Username__c FROM API_Integration_User__mdt WHERE DeveloperName = 'N26apiUser'];

    @HttpGet
    global static void getContactInfo(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        try{

            //we get the UUID from the url of the request
            String uuid = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

            //we ensure only the allowed user consumes the API
            if(UserInfo.getUserName() != USER_INTEGRATION.Username__c && !Test.isRunningTest()){
                throw new SecurityException( System.Label.APIRestGetContactInfo_NotAllowedError );
            }

            //get the contact related to the UUID
            List<Contact> contacts = [
                SELECT Id, Name, Product__c, Home_Country__c 
                FROM Contact 
                WHERE UUID__c = :uuid 
                LIMIT 1
            ];
            if (contacts.isEmpty()) {
                throw new DmlException( System.Label.APIRestGetContactInfo_ContactNotFoundError );
            }
            Contact contact = contacts[0];

            //get the product information related to the contact
            List<Product_Information__c> prodInfList = [SELECT Id, Name, Product__c, Home_Country__c, Charge_Type_Name__c, Value_Display__c 
                FROM Product_Information__c 
                WHERE Product__c = :contact.Product__c 
                AND Home_Country__c = :contact.Home_Country__c];

            if(prodInfList.isEmpty()){
                throw new DmlException(System.Label.APIRestGetContactInfo_NoProdInfoError);
            }


            //we build and return our return wrapper
            List<ProductInfoWrapper> productInfoList = new List<ProductInfoWrapper>();

            for (Product_Information__c pi : prodInfList) {
                productInfoList.add(new ProductInfoWrapper(pi.Charge_Type_Name__c, pi.Value_Display__c));
            }

            Map<String, Object> responseMap = new Map<String, Object>{
                'status' => 'success',
                'uuid' => uuid,
                'charges' => productInfoList
            };

            res.addHeader('Content-Type', 'application/json');
            res.responseBody = Blob.valueOf(JSON.serialize(responseMap));
            res.statusCode = 200;
        }catch (Exception e){
            //in case of error we return an error response
            Map<String, Object> errorResponse = new Map<String, Object>{
                'status' => 'error',
                'message' => e.getMessage()
            };
            res.addHeader('Content-Type', 'application/json');
            res.responseBody = Blob.valueOf(JSON.serialize(errorResponse));
            res.statusCode = 400;
        }
    }

    public class ProductInfoWrapper{
        public String type;
        public String value;
        public ProductInfoWrapper(String type, String value){
            this.type = type;
            this.value = value;
        }
    }
}