force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to specify the legal country of the contact</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to display the current products held in N26 related to the contact</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/Product_Information__c.object-meta.xml
<CustomObject>
    <description>Custom object used to display the current products information for contacts, based on the plan type and their specific home country</description>
    <label>Product Information</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Product Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Information__c/fields/Charge_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type_Name__c</fullName>
    <description>Formula field to display the related lookup object Charge Type name</description>
    <formula>Type__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Home Country record</description>
    <label>Home Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related product record</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Information</relationshipLabel>
    <relationshipName>Products_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Information__c/fields/Value_Display__c.field-meta.xml
<CustomField>
    <fullName>Value_Display__c</fullName>
    <description>This field is generated automatically based on the values added</description>
    <formula>IF( 
   RecordType.Name = &quot;Fee&quot;,
   IF(
      Value_Percent__c = 0, 
      &quot;Free&quot;, 
      TEXT(Value_Percent__c*100) &amp; &quot;%&quot;),

   IF(
      Not_Applicable__c, 
      &quot;N/a&quot;,
      IF(
         Value_Number__c-FLOOR(Value_Number__c)=0,
         Currency_Symbol__c &amp; &quot; &quot; &amp; SUBSTITUTE(TEXT( ROUND(Value_Number__c, 2)),&quot;.&quot;,&quot;,&quot;),
         Currency_Symbol__c &amp; &quot; &quot; &amp; SUBSTITUTE(TEXT(FLOOR(Value_Number__c)) &amp; &quot;.&quot; &amp; LPAD(TEXT((Value_Number__c - FLOOR(Value_Number__c)) * 100), 2, &quot;0&quot;),&quot;.&quot;,&quot;,&quot;)
         )
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field is generated automatically based on the values added</inlineHelpText>
    <label>Value Display</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayContactProdInfCaseController.cls
public with sharing class DisplayContactProdInfCaseController {
    
    @AuraEnabled
    public static CaseProductInfoResponse getContactProdInfDetails(Id caseId) {
        CaseProductInfoResponse response = new CaseProductInfoResponse();

        Case caseRecord;

        //based on the caseId we get the contact and its product fields
        try {
            caseRecord = [
                SELECT Id, ContactId, Contact.Product__c, Contact.Home_Country__c
                FROM Case
                WHERE Id = :caseId
            ];
        } catch (QueryException qe) {
            //no case id
            response.setError(System.Label.DisplayContactProdInfCaseController_NoIdError);
            return response;
        }

        //no contact Id
        if (caseRecord.ContactId == null) {
            response.setError(System.Label.DisplayContactProdInfCaseController_NoContactError);
            return response;
        }

        //no product or home country in contact
        if (caseRecord.Contact.Product__c == null || caseRecord.Contact.Home_Country__c == null) {
            response.setError(System.Label.DisplayContactProdInfCaseController_NoProdCountryError);
            return response;
        }

        //we get the product information 
        List<Product_Information__c> prodInfList = [
            SELECT Id, Name, Product__c, Home_Country__c, Charge_Type_Name__c, Value_Display__c
            FROM Product_Information__c
            WHERE Product__c = :caseRecord.Contact.Product__c
            AND Home_Country__c = :caseRecord.Contact.Home_Country__c
        ];

        //no product info for that contact product and country
        if (prodInfList.isEmpty()) {
            response.setError(System.Label.DisplayContactProdInfCaseController_NoProdInfError);
            return response;
        }

        // we generate our return wrapper list
        for (Product_Information__c pi : prodInfList) {
            response.productInfoList.add(new ProductInfoWrapper(pi.Charge_Type_Name__c, pi.Value_Display__c));
        }

        return response;
    }

    // ------------------------- return wrappers ---------------------------

    public class ProductInfoWrapper {

        @AuraEnabled public String type;
        @AuraEnabled public String value;

        public ProductInfoWrapper(String type, String value) {
            this.type = type;
            this.value = value;
        }
    }

    public class CaseProductInfoResponse {

        @AuraEnabled public List<ProductInfoWrapper> productInfoList { get; private set; }
        @AuraEnabled public String errorMessage { get; private set; }

        public CaseProductInfoResponse() {
            productInfoList = new List<ProductInfoWrapper>();
            errorMessage = '';
        }
        public void setError(String message) {
            this.errorMessage = message;
        }
    }
}